
name: school-management

services:
  school-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SCHOOL_ENVIRONMENT=dev
      - DB_URL=postgresql+asyncpg://postgres:example@school-db:5432/school
      - JWT_SECRET_KEY=1a9a444f13a975cb125b74e24c3a9a741d9a45294c01c0462b6167c232f47915
      - JWT_EXPIRATION_MINUTES=30
      - PYTHONDONTWRITEBYTECODE=1
    depends_on:
      - school-db
    pull_policy: never
    volumes:
      - ./mount:/mount

  school-db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: school
    ports:
      - "5432:5432"

  school-pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@xyz.com
      - PGADMIN_DEFAULT_PASSWORD=example
    ports:
      - "8888:80"
